###################################################################
#                                                                 #
#                        GATE simulation                          #
#                                                                 #
###################################################################
#
#------------------------------------------------------------------ 
# VERBOSE
#------------------------------------------------------------------ 


/control/execute                   mac/visualize/verbosity.mac

# ============================
# == LOAD DATABASE           ==
# ===========================
/gate/geometry/setMaterialDatabase    data/GateMaterials.db

#------------------------------------------------------------------ 
# GEOMETRY
#------------------------------------------------------------------ 


/control/execute                  mac/NewGeo.mac


#------------------------------------------------------------------ 
# PHYSICS
#------------------------------------------------------------------ 
#/gate/physics/addPhysicsList emstandard_opt4

/gate/physics/addPhysicsList QGSP_BIC_HP_EMZ


/gate/physics/Gamma/SetCutInRegion      world 1 mm
/gate/physics/Electron/SetCutInRegion   world 1 mm
/gate/physics/Positron/SetCutInRegion   world 1 mm


/gate/physics/Gamma/SetCutInRegion      layer_1 0.01 cm
/gate/physics/Electron/SetCutInRegion   layer_1 0.01 cm
/gate/physics/Positron/SetCutInRegion   layer_1 0.01 cm

/gate/physics/Gamma/SetCutInRegion      layer_2 0.01 cm
/gate/physics/Electron/SetCutInRegion   layer_2 0.01 cm
/gate/physics/Positron/SetCutInRegion   layer_2 0.01 cm

/gate/physics/Gamma/SetCutInRegion      layer_11 0.01 cm
/gate/physics/Electron/SetCutInRegion   layer_11 0.01 cm
/gate/physics/Positron/SetCutInRegion   layer_11 0.01 cm

/gate/physics/Gamma/SetCutInRegion      layer_12 0.01 cm
/gate/physics/Electron/SetCutInRegion   layer_12 0.01 cm
/gate/physics/Positron/SetCutInRegion   layer_12 0.01 cm


/gate/physics/Gamma/SetCutInRegion      layer_13 0.01 cm
/gate/physics/Electron/SetCutInRegion   layer_13 0.01 cm
/gate/physics/Positron/SetCutInRegion   layer_13 0.01 cm

/gate/physics/Gamma/SetCutInRegion      layer_14 0.01 cm
/gate/physics/Electron/SetCutInRegion   layer_14 0.01 cm
/gate/physics/Positron/SetCutInRegion   layer_14 0.01 cm

#=============================
#== ACTORs
#==========================================

/gate/actor/addActor               SimulationStatisticActor stat
/gate/actor/stat/save              output/stat.txt
/gate/actor/stat/saveEveryNSeconds 10

/gate/actor/addActor EnergySpectrumActor spec
/gate/actor/spec/save output/EnergySpectruminWaterNew.root
/gate/actor/spec/energySpectrum/setEmin 0 eV
/gate/actor/spec/energySpectrum/setEmax 10 MeV
/gate/actor/spec/energySpectrum/setNumberOfBins 10000

#/gate/actor/addActor LETActor let
#/gate/actor/let/save output/myLETactor.mhd
#/gate/actor/let/attachTo phantom
#/gate/actor/let/setResolution 1 1 100
#/gate/actor/let/setType DoseAveraged

#/gate/actor/addActor SecondaryProductionActor second
#/gate/actor/second/save output/secondary.root
#/gate/actor/second/attachTo phantom


##CCMod

#/control/execute                   mac/actor/CCMod_head.mac

/control/execute                   mac/actor/CCMod_head_adder.mac

#------------------------------------------------------------------ 
# INITIALIZE
#------------------------------------------------------------------ 
/gate/run/initialize


#------------------------------------------------------------------ 
# VISUALIZATION
#------------------------------------------------------------------ 
#/control/execute                     mac/visualize/visu.mac

#------------------------------------------------------------------ 
# SOURCE
#------------------------------------------------------------------ 

/control/execute                      mac/Protonbeam.mac

#/control/execute                      mac/pointgamma_isocenter_mono.mac

#/control/execute                      mac/Twopointgamma_isocenter.mac

#/control/execute                      mac/source.mac


# ============================
# == OUTPUT                ==
# ============================

/gate/application/noGlobalOutput

#------------------------------------------------------------------
#====================================================
#  R A N D O M   E N G I N E  A N D  S E E D
#====================================================
/control/execute                   mac/seed/SetSeed_MersenneTwister.mac


#=====================================================
#   M E A S U R E M E N T   S E T T I N G S   
#=====================================================

#/gate/application/setTimeSlice  1 s
#/gate/application/setTimeStart   0.00   s
#/gate/application/setTimeStop    1 s

#### 10e10
#/gate/application/setTotalNumberOfPrimaries 24548400

#### 2X10e9
#/gate/application/setTotalNumberOfPrimaries 4909680

#### 10e9
#/gate/application/setTotalNumberOfPrimaries 2454840

#/gate/application/setTotalNumberOfPrimaries 1810000

/gate/application/setTotalNumberOfPrimaries 100000000

/gate/application/startDAQ

exit

