# TWO POINT SOURCES

/gate/source/addSource pointsource gps
/gate/source/pointsource/gps/particle gamma
/gate/source/pointsource/gps/pos/type Point
/gate/source/pointsource/gps/pos/centre 0. 20. 0. mm
/gate/source/pointsource/gps/energytype Mono
/gate/source/pointsource/gps/monoenergy 4.44 MeV
/gate/source/pointsource/gps/angtype iso


/gate/source/addSource pointsource1 gps
/gate/source/pointsource1/gps/particle gamma
/gate/source/pointsource1/gps/pos/type Point
/gate/source/pointsource1/gps/pos/centre 0. -20. 0. mm
/gate/source/pointsource1/gps/energytype Mono
#/gate/source/pointsource1/gps/monoenergy 1.63 MeV
/gate/source/pointsource1/gps/monoenergy 4.44 MeV
/gate/source/pointsource1/gps/angtype iso