# WORLD INITIALIZATION

/gate/world/geometry/setXLength 1100. mm
/gate/world/geometry/setYLength 1100. mm
/gate/world/geometry/setZLength 1500. mm
/gate/world/vis/forceWireframe 1
/gate/world/vis/forceSolid 0
/gate/world/vis/setColor black
/gate/world/vis/setVisible false



# HEAD (4x MODULES)

/gate/world/daughters/name head
/gate/world/daughters/insert box
/gate/head/placement/setTranslation 384.0 0.0 0.0 mm
/gate/head/geometry/setXLength 450. mm
/gate/head/geometry/setYLength 500. mm
/gate/head/geometry/setZLength 740. mm
/gate/head/setMaterial Air
/gate/head/vis/forceWireframe 1
/gate/head/vis/forceSolid 0
/gate/head/vis/setColor red
/gate/head/vis/setVisible false


# MODULE

/gate/head/daughters/name module1
/gate/head/daughters/insert box
/gate/module1/placement/setTranslation 0.0 0.0 0.0 mm
/gate/module1/geometry/setXLength 450. mm
/gate/module1/geometry/setYLength 500. mm
/gate/module1/geometry/setZLength 736. mm
/gate/module1/setMaterial Air
/gate/module1/vis/forceWireframe 1
/gate/module1/vis/forceSolid 0
/gate/module1/vis/setColor blue
/gate/module1/vis/setVisible false


# CRYSTAL (STRIP)

/gate/module1/daughters/name crystal1
/gate/module1/daughters/insert box
/gate/crystal1/placement/setTranslation 0.0 0.0 0.0 mm
/gate/crystal1/geometry/setXLength 450. mm
/gate/crystal1/geometry/setYLength 500. mm
/gate/crystal1/geometry/setZLength 91. mm 
/gate/crystal1/setMaterial Air
/gate/crystal1/vis/forceWireframe 1
/gate/crystal1/vis/forceSolid 0
/gate/crystal1/vis/setColor green
/gate/crystal1/vis/setVisible false

# LAYER1 MODULE

#layer1 container
/gate/crystal1/daughters/name layer_core1
/gate/crystal1/daughters/insert box
/gate/layer_core1/placement/setTranslation -172.0 0.0 0.0 mm
/gate/layer_core1/geometry/setXLength 24. mm
/gate/layer_core1/geometry/setYLength 500. mm
/gate/layer_core1/geometry/setZLength 91. mm
/gate/layer_core1/setMaterial Air
/gate/layer_core1/vis/forceWireframe 1
/gate/layer_core1/vis/setColor yellow


/gate/layer_core1/daughters/name layer_1
/gate/layer_core1/daughters/insert box
/gate/layer_1/placement/setTranslation 0.0 0.0 0.0 mm
/gate/layer_1/geometry/setXLength 24. mm
/gate/layer_1/geometry/setYLength 500. mm
/gate/layer_1/geometry/setZLength 6. mm
/gate/layer_1/setMaterial EJ230
#/gate/layer_1/vis/forceWireframe 1
/gate/layer_1/vis/forceSolid 1
/gate/layer_1/vis/setColor magenta

# LAYER1 REPEATER 

/gate/layer_1/repeaters/insert cubicArray
/gate/layer_1/cubicArray/setRepeatNumberX 1
/gate/layer_1/cubicArray/setRepeatNumberY 1
/gate/layer_1/cubicArray/setRepeatNumberZ 13      
/gate/layer_1/cubicArray/setRepeatVector 0. 0. 7.0 mm   

# LAYER2 MODULE
#layer2 container
/gate/crystal1/daughters/name layer_core2
/gate/crystal1/daughters/insert box
/gate/layer_core2/placement/setTranslation -48.0 0.0 0.0 mm
/gate/layer_core2/geometry/setXLength 24. mm
/gate/layer_core2/geometry/setYLength 500. mm
/gate/layer_core2/geometry/setZLength 91. mm
/gate/layer_core2/setMaterial Air
/gate/layer_core2/vis/forceWireframe 1
/gate/layer_core2/vis/setColor yellow

/gate/layer_core2/daughters/name layer_11
/gate/layer_core2/daughters/insert box
/gate/layer_11/placement/setTranslation 0.0 0.0 0.0 mm
/gate/layer_11/geometry/setXLength 24. mm
/gate/layer_11/geometry/setYLength 500. mm
/gate/layer_11/geometry/setZLength 6. mm
/gate/layer_11/setMaterial EJ230
/gate/layer_11/vis/forceWireframe 1
/gate/layer_11/vis/forceSolid 1
/gate/layer_11/vis/setColor magenta

# LAYER11 REPEATER 

/gate/layer_11/repeaters/insert cubicArray
/gate/layer_11/cubicArray/setRepeatNumberX 1
/gate/layer_11/cubicArray/setRepeatNumberY 1
/gate/layer_11/cubicArray/setRepeatNumberZ 13      
/gate/layer_11/cubicArray/setRepeatVector 0. 0. 7.0 mm   

# LAYER3 MODULE
#layer3 container
/gate/crystal1/daughters/name layer_core3
/gate/crystal1/daughters/insert box
/gate/layer_core3/placement/setTranslation 112.0 0.0 0.0 mm
/gate/layer_core3/geometry/setXLength 96. mm
/gate/layer_core3/geometry/setYLength 500. mm
/gate/layer_core3/geometry/setZLength 91. mm
/gate/layer_core3/setMaterial Air
/gate/layer_core3/vis/forceWireframe 1
/gate/layer_core3/vis/setColor yellow

/gate/layer_core3/daughters/name layer_2
/gate/layer_core3/daughters/insert box
/gate/layer_2/placement/setTranslation 0.0 0.0 0.0 mm
/gate/layer_2/geometry/setXLength 24. mm
/gate/layer_2/geometry/setYLength 500. mm
/gate/layer_2/geometry/setZLength 6. mm
/gate/layer_2/setMaterial EJ230
/gate/layer_2/vis/forceWireframe 1
/gate/layer_2/vis/forceSolid 1
/gate/layer_2/vis/setColor magenta

# LAYER2 REPEATER 

/gate/layer_2/repeaters/insert cubicArray
/gate/layer_2/cubicArray/setRepeatNumberX 4
/gate/layer_2/cubicArray/setRepeatNumberY 1
/gate/layer_2/cubicArray/setRepeatNumberZ 13      
/gate/layer_2/cubicArray/setRepeatVector 24. 0. 7.0 mm   

# CRYSTAL (STRIP) REPEATER 

/gate/crystal1/repeaters/insert cubicArray
/gate/crystal1/cubicArray/setRepeatNumberX 1
/gate/crystal1/cubicArray/setRepeatNumberY 1
/gate/crystal1/cubicArray/setRepeatNumberZ 8
/gate/crystal1/cubicArray/setRepeatVector 0. 0. 92. mm

# MODULE REPEATER 

#/gate/module1/repeaters/insert cubicArray
#/gate/module1/cubicArray/setRepeatNumberX 1
#/gate/module1/cubicArray/setRepeatNumberY 1
#/gate/module1/cubicArray/setRepeatNumberZ 5
#/gate/module1/cubicArray/setRepeatVector 0. 0. 92. mm



#HEAD REPEATER

#/gate/head/repeaters/insert ring
#/gate/head/ring/setFirstAngle 0 degree
#/gate/head/ring/setRepeatNumber 2
#/gate/head/ring/enableAutoRotation







