
# POINT SOURCE

/gate/source/addSource pointsource gps
/gate/source/pointsource/gps/particle gamma
/gate/source/pointsource/gps/pos/type Point
/gate/source/pointsource/gps/pos/centre 0. 0. 0. mm
/gate/source/pointsource/gps/energytype Mono
/gate/source/pointsource/gps/monoenergy 4.44 MeV
/gate/source/pointsource/gps/angtype iso

#/gate/source/pointsource/gps/mintheta 73.13. deg
#/gate/source/pointsource/gps/maxtheta 106.87. deg

#/gate/source/pointsource/gps/minphi 140.19 deg
#/gate/source/pointsource/gps/maxphi 219.81 deg

#/gate/source/addSource pointsource1 gps
#/gate/source/pointsource1/gps/particle gamma
#/gate/source/pointsource1/gps/pos/type Point
#/gate/source/pointsource1/gps/pos/centre 12.25 -10. 0. mm
#/gate/source/pointsource1/gps/energytype Mono
#/gate/source/pointsource1/gps/monoenergy 1.63 MeV
#/gate/source/pointsource1/gps/angtype iso