# PENCIL BEAM SOURCE

/gate/source/addSource beam PencilBeam
/gate/source/beam/setParticleType proton
/gate/source/beam/setEnergy 150 MeV
/gate/source/beam/setSigmaEnergy 1.010865 MeV
#/gate/source/beam/setPosition 0. 0. -600.0 mm
/gate/source/beam/setPosition 0. 0. -132.5 mm
/gate/source/beam/setSigmaX 5.573300 mm
/gate/source/beam/setSigmaY 3.854700 mm
/gate/source/beam/setSigmaTheta 6.153100 mrad
/gate/source/beam/setSigmaPhi 4.153400 mrad
/gate/source/beam/setEllipseXThetaEmittance 77.119000 mm*mrad
/gate/source/beam/setEllipseXThetaRotationNorm positive
/gate/source/beam/setEllipseYPhiEmittance 50.064000 mm*mrad
/gate/source/beam/setEllipseYPhiRotationNorm positive
#/gate/source/beam/visualize 20 red 5