/gate/output/root/enable
/gate/output/root/setFileName             output/test

/gate/output/root/setRootHitFlag 1
/gate/output/root/setRootSinglesFlag 0
#/gate/output/root/verbose 1
#/gate/output/root/describe

#/gate/output/ascii/enable
#/gate/output/ascii/setFileName             output/test

#/gate/output/ascii/setOutFileHitsFlag 1
#/gate/output/ascii/setOutFileSinglesFlag 0
#/gate/output/ascii/verbose 1
#/gate/output/ascii/describe
	
