# POINT SOURCE

#/gate/source/addSource twogamma
#/gate/source/twogamma/setType backtoback

#/gate/source/twogamma/gps/type Point
#/gate/source/twogamma/gps/centre 0. 0. 0. mm
#/gate/source/twogamma/gps/particle gamma
#/gate/source/twogamma/gps/energytype Mono
#/gate/source/twogamma/gps/monoenergy 511 keV
#/gate/source/twogamma/gps/angtype iso
#/gate/source/twogamma/gps/mintheta 90. deg
#/gate/source/twogamma/gps/maxtheta 90. deg
#/gate/source/twogamma/gps/minphi 0. deg
#/gate/source/twogamma/gps/maxphi 360. deg

#/gate/source/twogamma/visualize 2000 magenta 5

/gate/source/addSource pointsource gps
/gate/source/pointsource/gps/particle gamma
/gate/source/pointsource/gps/pos/type Point
/gate/source/pointsource/gps/pos/centre 12.25 0. 0. mm
/gate/source/pointsource/gps/energytype Mono
/gate/source/pointsource/gps/monoenergy 4.44 MeV
/gate/source/pointsource/gps/angtype iso

# the parameters below if you want the source to emit in an XY (transverse) plane

#/gate/source/pointsource/gps/mintheta 90. deg
#/gate/source/pointsource/gps/maxtheta 90. deg

# the solid angle confined to the strip for source dist. 200mm and length of strip 500mm along y axis

#/gate/source/pointsource/gps/minphi 128.66 deg
#/gate/source/pointsource/gps/maxphi 231.34 deg

# the solid angle confined to the strip for source dist. 300mm and length of strip 500mm along y axis

#/gate/source/pointsource/gps/minphi 140.19 deg
#/gate/source/pointsource/gps/maxphi 219.81 deg

#/gate/source/pointsource/visualize 20 green 2

#/gate/source/pointsource/gps/mintheta 67.5 deg
#/gate/source/pointsource/gps/maxtheta 112.5 deg
#/gate/source/pointsource/gps/minphi 157.5 deg
#/gate/source/pointsource/gps/maxphi 202.5 deg

#/gate/source/pointsource/gps/pos/type Beam
#/gate/source/pointsource/gps/pos/shape Circle
#/gate/source/pointsource/gps/pos/radius 8 mm
#/gate/source/pointsource/gps/ene/mono 1 MeV
#/gate/source/pointsource/gps/ang/type focused
#/gate/source/pointsource/gps/ang/focuspoint 0 0 10 cm