/gate/physics/addPhysicsList QGSP_BIC_HP_EMY

#QGSP_BIC_HP
#QGSP_BERT_HP_EMZ
#QGSP_INCLXX_HP_EMY for prompt gamma
#emstandard_opt3
#QBBC_EMY suggested by Loic Grevoilt

/gate/physics/ActivateStepLimiter proton
/gate/physics/ActivateStepLimiter deuteron
/gate/physics/ActivateStepLimiter triton
/gate/physics/ActivateStepLimiter alpha
/gate/physics/ActivateStepLimiter GenericIon
/gate/physics/ActivateStepLimiter e-

/gate/physics/Gamma/SetCutInRegion world 1 mm
/gate/physics/Electron/SetCutInRegion world 1 mm
/gate/physics/Positron/SetCutInRegion world 1 mm

/gate/physics/SetMaxStepSizeInRegion world 1 mm

/gate/physics/Gamma/SetCutInRegion      phantom 0.1 mm
/gate/physics/Electron/SetCutInRegion   phantom 0.1 mm
/gate/physics/Positron/SetCutInRegion   phantom 0.1 mm

/gate/physics/addProcess RadioactiveDecay
/gate/physics/addProcess Decay

/gate/physics/processList Enabled
/gate/physics/processList Initialized

/gate/physics/displayCuts
#/gate/physics/print output/physics.txt
